export enum CosmeticTypes {
  AthenaCharacter = "AthenaCharacter",
  AthenaBackpack = "AthenaBackpack",
  AthenaPickaxe = "AthenaPickaxe",
  AthenaGlider = "AthenaGlider",
  AthenaDance = "AthenaDance",
  AthenaToy = "AthenaToy",
  AthenaEmoji = "AthenaEmoji",
  AthenaItemWrap = "AthenaItemWrap",
  AthenaMusicPack = "AthenaMusicPack",
  AthenaPet = "AthenaPet",
  AthenaPetCarrier = "AthenaPetCarrier",
  AthenaLoadingScreen = "AthenaLoadingScreen",
  AthenaSkyDiveContrail = "AthenaSkyDiveContrail",
}
